name: imagePRlevel

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      commitSHA:
        description: "pr commit SHA"
        required: true

permissions:
  contents: read

jobs:
  image_build_for_specific_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        ref: ${{ github.event.inputs.commitSHA }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
    - name: Login to Quay
      uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
      with:
        registry: quay.io/sustainable_computing_io
        username: ${{ secrets.BOT_NAME }}
        password: ${{ secrets.BOT_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
      with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: quay.io/sustainable_computing_io/kepler
          labels: ${{ github.event.inputs.commitSHA }}
          file: build/Dockerfile.libbpf.kepler
