name: image

on:
  workflow_call:
    inputs:
      imageTag:
        default: 'latest'
        type: string
      pushImage:
        default: true
        type: boolean
    secrets:
      username:
        required: true
      password:
        required: true

permissions:
  contents: read

jobs:
  image_build:
    permissions:
      actions: write  # for anchore/sbom-action to upload workflow artifacts
      contents: write  # for anchore/sbom-action to upload & delete release assets
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - IMAGE_NAME: kepler
          IMAGE_FILE: build/Dockerfile
          PLATFORMS:  linux/amd64,linux/arm64
          BUILD_ARGS: |
                INSTALL_DCGM=false
                INSTALL_HABANA=false
                VERSION=${{ inputs.imageTag }}
          LABEL:      ${{ inputs.imageTag }}
        - IMAGE_NAME: kepler
          IMAGE_FILE: build/Dockerfile
          PLATFORMS:  linux/amd64
          BUILD_ARGS: |
                INSTALL_DCGM=true
                INSTALL_HABANA=false
                VERSION=${{ inputs.imageTag }}-dcgm
          LABEL:      ${{ inputs.imageTag }}-dcgm
        - IMAGE_NAME: kepler
          IMAGE_FILE: build/Dockerfile
          PLATFORMS:  linux/amd64
          BUILD_ARGS: |
                INSTALL_DCGM=false
                INSTALL_HABANA=true
                VERSION=${{ inputs.imageTag }}-habana
          LABEL:      ${{ inputs.imageTag }}-habana
        - IMAGE_NAME: kepler-validator
          IMAGE_FILE: build/Dockerfile.kepler-validator
          BUILD_ARGS: ""
          PLATFORMS:  linux/amd64
          LABEL:      ${{ inputs.imageTag }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      with:
        image: tonistiigi/binfmt:qemu-v8.1.5
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
    - name: Login to Quay
      if: ${{ inputs.pushImage }}
      uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
      with:
        registry: quay.io/sustainable_computing_io
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}

    - name: Build and push image
      uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
      with:
          context: .
          platforms: ${{matrix.PLATFORMS}}
          push: ${{ inputs.pushImage }}
          build-args: ${{matrix.BUILD_ARGS}}
          tags: quay.io/sustainable_computing_io/${{matrix.IMAGE_NAME}}:${{matrix.LABEL}}
          labels: ${{matrix.LABEL}}
          file: ${{matrix.IMAGE_FILE}}

    - name: Generate SBOM
      uses: anchore/sbom-action@ab5d7b5f48981941c4c5d6bf33aeb98fe3bae38c # v0.15.10
      with:
        image: quay.io/sustainable_computing_io/${{matrix.IMAGE_NAME}}:${{matrix.LABEL}}
        artifact-name: sbom-${{matrix.IMAGE_NAME}}-${{matrix.LABEL}}.json
        output-file: ./sbom-${{matrix.IMAGE_NAME}}-${{matrix.LABEL}}.spdx.json

    - name: save Kepler image SBOM as artifact
      if: ${{ inputs.pushImage }}
      uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
      with:
          name: sbom-${{matrix.IMAGE_NAME}}-${{matrix.LABEL}}.spdx.json
          path: ./sbom-${{matrix.IMAGE_NAME}}-${{matrix.LABEL}}.spdx.json
          retention-days: 1
