name: Platform Validation

on:
  workflow_dispatch:

env:
  OUTPUT_DIR: "_output/"
  KEPLER_FILE_NAME: "kepler.tar.gz"
  VALIDATOR_FILE_NAME: "validator.tar.gz"
  ARTIFACT_DIR: "/tmp/artifacts"

jobs:
  build-artifacts:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      - name: Login to Quay
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: quay.io/sustainable_computing_io
          username: ${{ secrets.BOT_NAME }}
          password: ${{ secrets.BOT_TOKEN }}

      - name: Install Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod

      - name: Build and export Kepler image with test specific tag
        run: |
          make build_containerized
          make save-image
        env:
          IMAGE_REPO: "localhost:5001"
          IMAGE_NAME: "kepler"
          IMAGE_TAG: "platform-validation"
          CTR_CMD: docker
          IMAGE_OUTPUT_PATH: ${{env.OUTPUT_DIR}}${{env.KEPLER_FILE_NAME}}

      - name: Save Kepler image as artifact
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: kepler
          path: ${{env.OUTPUT_DIR}}${{env.KEPLER_FILE_NAME}}
          retention-days: 1

      - name: Build and push kepler-validator to official group repo with latest tag
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: quay.io/sustainable_computing_io/kepler-validator:latest
          labels: latest
          file: build/Dockerfile.kepler-validator

      - name: Build and export kepler-validator image with test specific tag
        run: |
          make build-validation-container
          make save-image
        env:
          IMAGE_REPO: "localhost:5001"
          IMAGE_NAME: "kepler-validator"
          IMAGE_TAG: "x86-rapl"
          CTR_CMD: docker
          IMAGE_OUTPUT_PATH: ${{env.OUTPUT_DIR}}${{env.VALIDATOR_FILE_NAME}}

      - name: Save kepler-validator test image as artifact
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: validator
          path: ${{env.OUTPUT_DIR}}${{env.VALIDATOR_FILE_NAME}}
          retention-days: 1

  platform_validation_test:
    needs: [build-artifacts]
    runs-on: [self-hosted, linux, x64]
    strategy:
      matrix:
        cluster_provider: [kind]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Download Kepler test image artifact
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: kepler

      - name: Download kepler-validator test image artifact
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: validator

      - name: Build manifest
        run: make build-manifest OPTS="CI_DEPLOY PROMETHEUS_DEPLOY"
        env:
          CLUSTER_PROVIDER: ${{matrix.cluster_provider}}
          IMAGE_REPO: "localhost:5001"
          IMAGE_TAG: "platform-validation"
          CTR_CMD: docker

      - name: Import Kepler test image
        run: make load-image
        env:
          IMAGE_REPO: "localhost:5001"
          IMAGE_NAME: "kepler"
          IMAGE_TAG: "platform-validation"
          CTR_CMD: docker
          INPUT_PATH: ${{env.KEPLER_FILE_NAME}}

      - name: Import kepler-validator test image
        run: make load-image
        env:
          IMAGE_REPO: "localhost:5001"
          IMAGE_NAME: "kepler-validator"
          IMAGE_TAG: "x86-rapl"
          CTR_CMD: docker
          INPUT_PATH: ${{env.VALIDATOR_FILE_NAME}}

      - name: Get Node component power before deploy kind cluster
        run: |
          make get-power
        env:
          IMAGE_REPO: "localhost:5001"
          IMAGE_NAME: "kepler-validator"
          IMAGE_TAG: "x86-rapl"
          CTR_CMD: docker

      - name: Use Kepler action to deploy cluster
        uses: sustainable-computing-io/kepler-action@ce619a32f97caaf2fa22329e2cb5e0afc1760178 # v0.0.6
        with:
          cluster_provider: ${{matrix.cluster_provider}}
          ebpfprovider: libbpf
          local_dev_cluster_version: v0.0.3
          prometheus_enable: true
          grafana_enable: true

      - name: Push Kepler test image to local registry
        run: |
          make push-image
        env:
          IMAGE_REPO: "localhost:5001"
          IMAGE_NAME: "kepler"
          IMAGE_TAG: "platform-validation"
          CTR_CMD: docker

      - name: Push kepler-validator test image to local registry
        run: |
          make push-image
          make image-prune
        env:
          IMAGE_REPO: "localhost:5001"
          IMAGE_NAME: "kepler-validator"
          IMAGE_TAG: "x86-rapl"
          CTR_CMD: docker

      - name: Get Node component power before deploy kepler
        run: |
          make get-power
        env:
          IMAGE_REPO: "localhost:5001"
          IMAGE_NAME: "kepler-validator"
          IMAGE_TAG: "x86-rapl"
          CTR_CMD: docker

      - name: Deploy Kepler on cluster
        run: make cluster-deploy
        env:
          CLUSTER_PROVIDER: ${{matrix.cluster_provider}}
          NO_BUILDS: true

      - name: Save artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: artifacts
          path: ${{env.ARTIFACT_DIR}}
          retention-days: 10

      - name: Run platform validation test cases
        run: make platform-validation
        env:
          CLUSTER_PROVIDER: ${{matrix.cluster_provider}}
          IMAGE_REPO: "localhost:5001"
          IMAGE_NAME: "kepler-validator"
          IMAGE_TAG: "x86-rapl"
          CTR_CMD: docker
          kepler_address: localhost:9103
          prometheus_address: localhost:9091

      - name: Undeploy Kepler and cleanup the cluster
        run: |
          make cluster-clean
          make cluster-down
        env:
          CLUSTER_PROVIDER: ${{matrix.cluster_provider}}
