name: Pull request

on:
  branch_protection_rule:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'enhancements/**'
      - '*.md'

jobs:
  c:
    uses: ./.github/workflows/c.yml
  # for each PR run go command line check
  golang:
    uses: ./.github/workflows/golang.yml
  # for each PR run unit test
  unit_test:
    uses: ./.github/workflows/unit_test.yml
  # for each PR ensure for local developer usage
  developer_local:
    uses: ./.github/workflows/developer_local.yml
  # for each PR run integration test    
  integration_test:
    uses: ./.github/workflows/integration_test.yml

  changes_image:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit

    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      id: changes
      with:
        filters: |
          src:
            - './.github/workflows/image.yml'
            - './build/Dockerfile'
            - './build/Dockerfile.kepler-validator'

  image:
    needs: changes_image
    if: ${{ needs.changes_image.outputs.src == 'true' }}
    uses: ./.github/workflows/image.yml
    with:
      pushImage: false
    secrets:
        username: ${{ secrets.BOT_NAME }}
        password: ${{ secrets.BOT_TOKEN }}

  changes_baseimage:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit

    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      id: changes
      with:
        filters: |
          src:
            - './.github/workflows/image_base.yml'
            - './build/Dockerfile.builder'
